stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compilando codigo..."
    - "mvn clean compile"

test-junit-job:
  stage: test
  dependencies:
    - build-job
  script:
    - echo "Testando Codigo"
    - "mvn package"